config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", :as => :rails_health_check

  resources :links
  resources :views, path: :v, only: [:show]
  root "links#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  has_many :views, dependent: :destroy
  scope :recent_first, -> { order(created_at: :desc) }

  validates :url, presence: true

  after_save_commit if: :url_previously_changed? do
    MetadataJob.perform_later(to_param)
  end

  def self.find(id)
    super(ShortCode.decode(id))
  end

  def to_param
    ShortCode.encode(id)
  end

  def domain
    URI(url).host
  rescue
    URI::InvalidURIError
  end
end

app/models/metadata.rb
require "open-uri"

class Metadata
  attr_reader :doc

  def self.retrieve_from(url)
    new(URI.open(url))
  rescue
    new
  end

  def initialize(html = nil)
    @doc = Nokogiri::HTML(html)
  end

  def attributes
    {
      title: title,
      description: description,
      image: image
    }
  end

  def title
    doc.at_css("title")&.text
  end

  def description
    meta_tag_content "description"
  end

  def image
    meta_tag_content "og:image", name_attribute: :property
  end

  def meta_tag_content(name, name_attribute: :name)
    doc.at_css("meta[#{name_attribute}='#{name}']")&.attributes&.fetch("content", nil)&.text
  end

  #   def self.retrieve_from(url)
  #     metadata = LinkThumbnailer.generate(url)
  #     new(
  #       title: metadata.title,
  #       description: metadata.description,
  #       image_url: metadata.images.first.src.to_s
  #     )
  #   end

  #   attr_reader :title, :description, :image_url

  #   def initialize(title:, description:, image_url:)
  #     @title = title
  #     @description = description
  #     @image_url = image_url
  #   end
end

app/models/short_code.rb
class ShortCode
  ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".freeze
  BASE = ALPHABET.length

  def self.encode(integer)
    return ALPHABET[0] if integer == 0
    s = ""
    while integer > 0
      s << ALPHABET[integer.modulo(BASE)]
      integer /= BASE
    end
    s.reverse
  end

  def self.decode(string)
    i = 0
    string.each_char { |c| i = i * BASE + ALPHABET.index(c) }
    i
  end
end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :link, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def set_link
    @link = Link.find(params[:id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  def index
    @links = Link.recent_first
    @link ||= Link.new
  end

  def show
  end

  def edit
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.turbo_stream { render turbo_stream: turbo_stream.prepend("links", @link) }
      end
    else
      index
      render :index, status: :unprocessable_entity
    end
  end

  def update
    if @link.update(link_params)
      redirect_to @link
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @link.destroy
    redirect_to root_path, notice: "Link was successfully destroyed."
  end

  private

  def link_params
    params.require(:link).permit(:url)
  end
end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  before_action :set_link

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to root_path, alert: "Missing link!"
  end

  def show
    @link.views.create(ip: request.ip, user_agent: request.user_agent)
    @link.broadcast_replace_to(@link)

    redirect_to @link.url, allow_other_host: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favicon_helper.rb
module FaviconHelper
  def google_favicon_url(domain)
    "https://www.google.com/s2/favicons?domain=#{domain}"
  end

  def domain_favicon_image_tag(domain, **)
    image_tag(google_favicon_url(domain), **)
  end
end

app/helpers/truncate_helper.rb
require "action_view/helpers/text_helper"

module TruncateHelper
  include ActionView::Helpers::TextHelper

  def truncate_title(text, length = 45)
    truncate(text, length: length, omission: "...")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Orange Shortner Links</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= vite_client_tag %>
    <%= vite_stylesheet_tag 'application', data: { "turbo-track": "reload" } %>
    <%= vite_javascript_tag 'application' %>
    <!--
      If using a TypeScript entrypoint file:
        vite_typescript_tag 'application'

      If using a .jsx or .tsx entrypoint, add the extension:
        vite_javascript_tag 'application.jsx'

      Visit the guide for more information: https://vite-ruby.netlify.app/guide/rails
    -->

  </head>

  <body>
    <nav class="bg-white border-gray-200 dark:bg-gray-900">
      <div class="flex flex-wrap justify-between items-center p-4 mx-auto max-w-screen-xl">
        <%= link_to root_path, class: 'flex items-center space-x-3 rtl:space-x-reverse' do %>
          <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo" />
          <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Orangelinks</span>
        <% end %>
        <div class="flex items-center space-x-3 md:order-2 md:space-x-0 rtl:space-x-reverse">
          <button type="button" class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
            <span class="sr-only">Open user menu</span>
            <img class="w-8 h-8 rounded-full" src="https://flowbite.com/docs/images/people/profile-picture-3.jpg" alt="user photo">
          </button>
          <!-- Dropdown menu -->
          <div class="hidden z-50 my-4 text-base list-none bg-white rounded-lg divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600" id="user-dropdown">
            <div class="px-4 py-3">
              <span class="block text-sm text-gray-900 dark:text-white">Bonnie Green</span>
              <span class="block text-sm text-gray-500 truncate dark:text-gray-400">name@flowbite.com</span>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <main class="px-5 mx-auto mt-14 prose">
      <%= tag.p alert, class: "px-4 py-2 text-sm font-medium text-yellow-800 bg-yellow-100 rounded" if alert %>
      <%= tag.p notice, class: "px-4 py-2 text-sm font-medium text-blue-800 bg-blue-100 rounded" if notice %>

      <%= yield %>
    </main>
  </body>

</html>

app/views/links/_form.html.erb
<%= form_with model: @link, data: { controller: 'reset-form', action: 'turbo:submit-end->reset-form#reset' } do |form| %>
  <div class="flex gap-2 items-center">
    <%= form.url_field :url, autofocus: true, required: true, placeholder: "https://example.org", class: "flex-grow rounded" %>
    <%= form.button "Save", class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
  </div>
<% end %>

app/views/links/_link.html.erb
<%= tag.div id: dom_id(link) do %>
  <%= turbo_stream_from link %>

  <div class="grid grid-cols-8 items-center py-4">
    <div class="col-span-5">

      <%= link_to view_path(link), target: :_blank, data: {turbo:false}, class: "flex flex-col items-start gap-1 no-underline" do %>
        <div class="flex gap-1 items-center">
          <%= domain_favicon_image_tag link.domain, class: 'm-0 inline-block' %>
          <%= truncate_title link.title || link.url %>
        </div>

        <%= tag.p link.description, class: "text-xs text-gray-700 m-0" %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="inline-block w-4 h-4">
          <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
        </svg>
      <% end%>
    </div>

    <div class="col-span-2 text-xs text-center">
      <%= link_to pluralize(link.views_count, 'view'), link, class: "text-gray-900 px-2 py-1.5 rounded bg-gray-100 no-underline" %>
    </div>

    <div class="text-xs text-center">
      <%= button_tag "Copy", class: "font-medium text-gray-900 px-2 py-1.5 rounded bg-gray-100 no-underline", data: { controller: "clipboard", clipboard_text: view_url(link) } %>
    </div>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Edit Link</h1>

<%= render partial: "form", locals: {link: @link} %>

<div class="flex gap-1 items-center mt-4">
  <%= link_to "Cancel", @link %>
  or
  <%= button_to "Delete", @link, method: :delete, data: {turbo_confirm: "Are you sure?"} %>
</div>

app/views/links/index.html.erb
<%= render partial: "form", locals: {link: @link} %>

<h2 class="mt-20">Last links</h2>
<div id="links" class="flex flex-col divide-y divide-gray-100">
  <%= render @links %>
</div>

app/views/links/show.html.erb
<%= link_to "← Back to all links", root_path, class: "no-underline text-xs px-3 py-2 rounded bg-gray-100" %>

<h1 class="mt-10 mb-5"><%= @link.url %></h1>

<div class="flex justify-between items-center mb-4 text-xs">
  <%= link_to view_path(@link), target: :_blank, data: {turbo:false}, class: "px-2 py-1.5 rounded bg-gray-100 flex items-center gap-1 no-underline" do %>
    <%= domain_favicon_image_tag @link.domain, class: 'inline-block m-0' %>
    <%= truncate_title(@link.url, 60) %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="inline-block w-4 h-4">
      <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
    </svg>
  <% end%>

  <div class="flex gap-2 items-center">
    <%= tag.div pluralize(@link.views_count, "view") %>
    <%= button_tag "Copy", class: "font-medium text-gray-900 px-2 py-1.5 rounded bg-gray-100 no-underline", data: { controller: "clipboard", clipboard_text: view_url(@link) } %>
    <%= link_to "Edit", edit_link_path(@link), class: "text-gray-900 px-2 py-1.5 rounded bg-gray-100 no-underline" %>
  </div>
</div>

<%= line_chart @link.views.group_by_day(:created_at, range: 2.weeks.ago..Time.now, expand_range: true).count %>